### ISSUE TITLE
cannot find ejs

### ISSUE THREAD

**Issue by zunnu** [Sgawrys/NodeScrim#10]
Hello!
Have to say this project seams cool thou i have problem with it I have used npm install and npm start but when I try to connect to port 8080 I get this error "Error: Cannot find module 'ejs'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at new View (/home/node2/node_modules/express/lib/view.js:50:49)
   at EventEmitter.app.render (/home/node2/node_modules/express/lib/application.js:545:12)
   at ServerResponse.res.render (/home/node2/node_modules/express/lib/response.js:938:7)
   at /home/node2/server.js:68:6
   at Layer.handle [as handle_request](/home/node2/node_modules/express/lib/router/layer.js:82:5)
   at next (/home/node2/node_modules/express/lib/router/route.js:110:13)"
and what config.js fields are needed all of them?

**Comment by Sgawrys** [comment]
Hi!

Fix for that issue would just be <code>npm install ejs --save</code> in the root directory of the project, I'm still new to NodeJS so I probably messed up the package.json, will fix! (If Node states you can't find any other modules, just run the same command and replace ejs with any other module names)

I'm glad you've taken the time to try and run it/set it up! I really appreciate it :)

Thanks,
Stefan

**Comment by zunnu** [comment]
Hello
Thanks for help i'm gonna test it soon :) Im new too my goals are to learn node js, java, and php that why i'm really interested about your project and I would like to try to add it to ebot that players could signup and make own lobbies and ebot would conf them would that be ok to you?

Date: Mon, 27 Apr 2015 11:41:13 -0700

**Comment by Sgawrys** [comment]
Hey,

I'm not quite familiar with e-bot, what would a project like that entail? Do you mean something along the lines of this project setting up the DigitalOcean server, and installing e-bot on that server for proper match configuration?

Thanks,
Stefan

**Comment by zunnu** [comment]
Yes but I don't use Digital Ocean server's see i'm keeping up Finland's biggest CSGO community and I just had tournament 2 days ago it went great I have customized ebot little bit but see the problem is that Finland community is really broken right now so I was thinking that I use all my skills and effort to make it better and this is one good way to  do it next is to make some kind team finding system to our website. 

Date: Mon, 27 Apr 2015 11:56:51 -0700
